int: 정수

In [4]:
a = 1; print(type(a))

<class 'int'>


float: 소수점

In [5]:
a = 1; a = float(a); print(type(a))

<class 'float'>


int(a)를 하면 a의 type이 다시 정수로 바뀜.

In [6]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


‘ 를 씌워주면 문자로 인식

In [7]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


[n] 대괄호를 치면 n 번째 문자가 나오는데, [0]이 첫 번째 글자

In [8]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


대괄호 안에 쉼표로 나열되어 있으면 type은 list

In [9]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


tuple도 위와 비슷함.

In [10]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


class‘dict'는 1:1 대응

In [11]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


type은 위와 마찬가지로 list, 그 밑 a가 그대로 나옴.

In [17]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

numpy는 가장 중요. 보통 np로 자주 불러냄.

In [13]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


원래 행렬이라면 안 되겠지만 array가 행렬 자체를 의미하는 것은 아니므로 29에서 곱하는 게 가능.

In [14]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


이번엔 np로 matrix 설정.

In [15]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


여기선 matrix이기 때문에 shapes(2,3)=2 by 3 행렬 간 곱을 했을 때 오류

In [16]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

.T를 하여 transpose 함으로써 곱 가능.

In [18]:
c*c.T

matrix([[14, 19],
        [19, 73]])